api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    
    collection:
        pagination:
 #          enabled: false
            page_parameter_name: _page
            client_enabled : true
            enabled_parameter_name : pagination
            items_per_page : 4
